version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
      POSTGRES_DB: foodgram_db
      POSTG-RES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432" # Пробрасываем порт, чтобы можно было подключиться к базе с компьютера

  backend:
    build: ./backend/
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    environment:
      # Прописываем переменные для локального запуска
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
      POSTGRES_DB: foodgram_db
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: 'my-local-secret-key-for-dev'
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    ports:
      - "8000:8000" # Пробрасываем порт, чтобы можно было делать запросы из Postman
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py load_ingredients &&
             gunicorn foodgram.wsgi:application --bind 0:8000"

volumes:
  pg_data:
  static_volume:
  media_volume:
