    version: '3.8'

    services:
      db:
        image: postgres:13.0-alpine
        restart: always
        volumes:
          - pg_data:/var/lib/postgresql/data/
        env_file: ./infra/.env

      backend:
        # Теперь он будет скачиваться с Docker Hub
        image: pavellagerev/foodgram_backend:latest
        restart: always
        volumes:
          - static_volume:/app/static/
          - media_volume:/app/media/
          - ./data/:/app/data/
        depends_on:
          - db
        env_file: ./infra/.env

      gateway:
        build:
          context: .
          dockerfile: ./infra/Dockerfile.gateway
        restart: always
        ports:
          - "8001:80"
        volumes:
          - static_volume:/usr/share/nginx/html/
          - media_volume:/var/html/media/
        depends_on:
          - backend
