version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: ./.env
    networks:
      - foodgram_network

  backend:
    build: ./backend/
    restart: always
    volumes:
      - django_static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file: ./.env
    networks:
      - foodgram_network
    entrypoint: ["/usr/local/bin/wait-for-postgres.sh", "db", "gunicorn", "foodgram.wsgi:application", "--bind", "0:8000"]

  frontend:
    build: ./frontend/
    command: sh -c "cp -r /app/build/. /app/frontend_static/"
    volumes:
      - frontend_static_volume:/app/frontend_static/
    networks:
      - foodgram_network

  gateway:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.gateway
    restart: always
    ports:
      - "8001:80"
    volumes:
      - django_static_volume:/app/static/
      - frontend_static_volume:/app/frontend_static/
      - media_volume:/app/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

volumes:
  pg_data:
  django_static_volume:
  frontend_static_volume:
  media_volume:

networks:
  foodgram_network:
    driver: bridge
