version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: ./infra/.env
    networks:
      - foodgram_network

  backend:
    build: ./backend/
    restart: always
    volumes:
      - static_volume:/app/collected_static/
      - media_volume:/app/media/
      - ./data/:/app/data/
    depends_on:
      - db
    env_file: ./infra/.env
    networks:
      - foodgram_network

  frontend:
    build: ./frontend/
    restart: always
    volumes:
      - static_volume:/app/build
    networks:
      - foodgram_network

  gateway:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.gateway
    restart: always
    ports:
      - "8088:80"
    volumes:
      - static_volume:/usr/share/nginx/html/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  foodgram_network:
    driver: bridge
