version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    # Используем environment вместо env_file для явного указания кодировки
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    networks:
      - foodgram_network

  backend:
    build: ./backend/
    restart: always
    volumes:
      - static_volume:/app/collected_static/ # Отдельная папка для статики
      - media_volume:/app/media/
    depends_on:
      - db
    env_file: ./.env
    networks:
      - foodgram_network
    entrypoint: ["/usr/local/bin/wait-for-postgres.sh", "db", "gunicorn", "foodgram.wsgi:application", "--bind", "0:8000"]

  frontend:
    build: ./frontend/
    volumes:
      - static_volume:/static_frontend/ # Копируем в отдельную папку в томе
    networks:
      - foodgram_network

  gateway:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.gateway
    restart: always
    ports:
      - "8001:80"
    volumes:
      - static_volume:/staticfiles/ # Подключаем общий том
      - media_volume:/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  foodgram_network:
    driver: bridge
