version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: ./.env
    networks:
      - foodgram_network

  backend:
    build: ./backend/
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file: ./.env
    networks:
      - foodgram_network

  frontend:
    build: ./frontend/
    # Эта команда скопирует собранные файлы в том и остановит контейнер
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static/
    networks:
      - foodgram_network

  gateway:
    build: ./infra/
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/
      - media_volume:/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  foodgram_network:
    driver: bridge
