version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: foodgram
      POSTGRES_PASSWORD: foodgram_password
      POSTGRES_DB: foodgram
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    restart: on-failure
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    environment:
      POSTGRES_USER: foodgram
      POSTGRES_PASSWORD: foodgram_password
      POSTGRES_DB: foodgram
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: 'local-secret-key'
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
volumes:
  pg_data:
