    version: '3.8'

    services:
      db:
        image: postgres:13.0-alpine
        restart: always
        volumes:
          - pg_data:/var/lib/postgresql/data/
        env_file: ./infra/.env
        networks:
          - foodgram_network

      backend:
        # Скачиваем готовый образ с Docker Hub
        image: pavellagerev/foodgram_backend:latest
        restart: always
        volumes:
          - static_volume:/app/static/
          - media_volume:/app/media/
          - ./data/:/app/data/
        depends_on:
          - db
        env_file: ./infra/.env
        networks:
          - foodgram_network

      gateway:
        build:
          context: .
          dockerfile: ./infra/Dockerfile.gateway
        restart: always
        ports:
          - "8001:80"
        volumes:
          - ./build:/usr/share/nginx/html
          - media_volume:/var/html/media/
        depends_on:
          - backend
        networks:
          - foodgram_network

    volumes:
      pg_data:
      media_volume:

    networks:
      foodgram_network:
        driver: bridge
