# Константы для валидации моделей
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
MAX_LENGTH_RECIPE_NAME = 200
MAX_LENGTH_TAG_NAME = 200
MAX_LENGTH_TAG_SLUG = 200
MAX_LENGTH_INGREDIENT_NAME = 200
MAX_LENGTH_INGREDIENT_UNIT = 200