# Используем официальный образ Nginx
FROM nginx:1.23.3-alpine

# Удаляем стандартную конфигурацию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем нашу конфигурацию, указывая полный путь от корня
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем статические файлы документации API
COPY docs/ /usr/share/nginx/html/api/docs/