# Используем базовый образ Nginx
FROM nginx:1.25-alpine

# Копируем наш кастомный конфиг Nginx
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем документацию (это можно оставить)
COPY docs/ /usr/share/nginx/html/api/docs/