version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:13.0-alpine
    container_name: foodgram-db
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - .env

  # Сервис нашего Django-бэкенда
  backend:
    build: ../backend/
    container_name: foodgram-backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  # Сервис для сборки фронтенда (запускается один раз)
  frontend:
    build: ../frontend/
    container_name: foodgram-frontend
    volumes:
      - frontend_build:/app/result_build

  # Сервис веб-сервера Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: foodgram-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

# Именованные volumes для сохранения данных
volumes:
  foodgram_db:
  static_volume:
  media_volume:
  frontend_build:
