services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: ./infra/.env
    networks:
      - foodgram_network

  backend:
    image: pavellagerev/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file: ./infra/.env
    networks:
      - foodgram_network

  frontend:
    image: pavellagerev/foodgram_frontend:latest
    volumes:
      - static_volume:/app/build

  gateway:
    image: pavellagerev/foodgram_gateway:latest
    restart: always
    ports:
      - "8001:80"
    volumes:
      - static_volume:/usr/share/nginx/html/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  foodgram_network:
    driver: bridge
